production:
  <<: *default
  database: <%= ENV['Sweets_Subsc'] %>
  adapter: mysql2
  encoding: utf8mb4
  charset: utf8mb4
  collation: utf8mb4_general_ci
  host: <%= ENV['rds-mysql-server.cdm2g0msmrgz.ap-northeast-1.rds.amazonaws.com'] %>
  username: <%= ENV['root'] %>
  password: <%= ENV['O0110akari'] %>
